# Generated by Django 5.0.4 on 2024-05-01 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='wiek',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='imie',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='zdjecie',
            new_name='photos',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='nazwisko',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='profil',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jakis.gender'),
        ),
        migrations.DeleteModel(
            name='Zgloszenie',
        ),
    ]
